# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Algorithm Test
email: site@macuco.com.br
description: "Loucuras com o Jekyll. É hora do show, porra"
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://raulfdm.github.io/algoritmo-sistemas-produtivos" # the base hostname & protocol for your site
twitter_username: raulfdm
github_username:  raulfdm

# Build settings
markdown: kramdown
highlighter: rouge
permalink: /:title/:id
